name: Lint on release publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  find:
    name: Find Docker images
    runs-on: ubuntu-latest
    outputs:
      docker_images: ${{ steps.docker_images.outputs.docker_images_list }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2

      - name: 🔍 Find docker images directories
        id: docker_images
        uses: ./.github/actions/find-docker-images

  build-and-push-image:
    name: Build and push docker image ${{ matrix.image }}
    runs-on: ubuntu-latest
    needs: find
    strategy:
      matrix:
        image: ${{ fromJson(needs.find.outputs.docker_images) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

